name: Build and release to chrome store
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn install
    - name: Build package
      run: yarn build
    - name: Create zip file
      uses: papeloto/action-zip@v1
      with:
        files: dist/
        dest: dist.zip